import {
  KeyboardEventListType,
  actionListType,
  actionMenu,
} from "../types/types";

export const actionTypes: actionMenu = {
  result: "result",
  clear: "clear",
  clearAll: "clearAll",
  calculation: "calculation",
};

export const buttonList: string[] = [
  "AC",
  "DE",
  ".",
  "/",
  "7",
  "8",
  "9",
  "*",
  "4",
  "5",
  "6",
  "-",
  "1",
  "2",
  "3",
  "+",
  "00",
  "0",
  "=",
];

export const actionList: actionListType = {
  AC: {
    id: "AC",
    className: "operator",
    title: "AC",
    type: actionTypes.clearAll,
    variant: "",
  },
  DE: {
    id: "DE",
    className: "operator",
    title: "DE",
    type: actionTypes.clear,
    variant: "",
  },
  ".": {
    id: ".",
    className: "operator",
    title: ".",
    type: actionTypes.calculation,
    variant: "",
  },
  "/": {
    id: "/",
    className: "operator",
    title: "/",
    type: actionTypes.calculation,
    variant: "",
  },
  7: {
    id: "7",
    className: "number",
    title: "7",
    type: actionTypes.calculation,
    variant: "",
  },
  8: {
    id: "8",
    className: "number",
    title: "8",
    type: actionTypes.calculation,
    variant: "",
  },
  9: {
    id: "9",
    className: "number",
    title: "9",
    type: actionTypes.calculation,
    variant: "",
  },
  "*": {
    id: "*",
    className: "operator",
    title: "*",
    type: actionTypes.calculation,
    variant: "",
  },

  4: {
    id: "4",
    className: "number",
    title: "4",
    type: actionTypes.calculation,
    variant: "",
  },

  5: {
    id: "5",
    className: "number",
    title: "5",
    type: actionTypes.calculation,
    variant: "",
  },
  6: {
    id: "6",
    className: "number",
    title: "6",
    type: actionTypes.calculation,
    variant: "",
  },

  "-": {
    id: "-",
    className: "operator",
    title: "-",
    type: actionTypes.calculation,
    variant: "",
  },
  1: {
    id: "1",
    className: "number",
    title: "1",
    type: actionTypes.calculation,
    variant: "",
  },
  2: {
    id: "2",
    className: "number",
    title: "2",
    type: actionTypes.calculation,
    variant: "",
  },
  3: {
    id: "3",
    className: "number",
    title: "3",
    type: actionTypes.calculation,
    variant: "",
  },
  "+": {
    id: "+",
    className: "operator",
    title: "+",
    type: actionTypes.calculation,
    variant: "",
  },
  "00": {
    id: "00",
    className: "number",
    title: "00",
    type: actionTypes.calculation,
    variant: "",
  },
  0: {
    id: "0",
    className: "number",
    title: "0",
    type: actionTypes.calculation,
    variant: "",
  },
  "=": {
    id: "=",
    className: "operator col-span-2",
    title: "=",
    type: actionTypes.result,
    variant: "",
  },
};

export const keyboardEventList: KeyboardEventListType = {
  Enter: actionList["="],
  Backspace: actionList.DE,
  Delete: actionList.DE,
  Escape: actionList.AC,
  AC: actionList.AC,
  DE: actionList.DE,
  ".": actionList["."],
  "/": actionList["/"],
  7: actionList[7],
  8: actionList[8],
  9: actionList[9],
  "*": actionList["*"],
  4: actionList[4],
  5: actionList[5],
  6: actionList[6],
  "-": actionList["-"],
  1: actionList[1],
  2: actionList[2],
  3: actionList[3],
  "+": actionList["+"],
  "00": actionList["00"],
  0: actionList[0],
  "=": actionList["="],
};
